# autogenerated


class Perceptron:
    def __init__(self, input_size):
        self.weights = [0.0] * input_size
        self.bias = 0.0

    def predict(self, inputs):
        return 1 if sum(w * x for w, x in zip(self.weights, inputs)) + self.bias > 0 else 0

    def train(self, inputs, target, learning_rate=0.1):
        prediction = self.predict(inputs)
        error = target - prediction
        self.weights = [w + learning_rate * error * x for w, x in zip(self.weights, inputs)]
        self.bias += learning_rate * error
